import type { Config } from "tailwindcss";

// Cyber-Sovereign design system — obsidian purple base, electric fuchsia +
// cyan neon accents, Geist type. Colors mirror the design tokens exactly.
export default {
  darkMode: "class",
  content: ["./app/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "surface-bright": "#3c3648",
        secondary: "#d3fbff",
        "surface-container": "#221d2e",
        error: "#ffb4ab",
        background: "#161121",
        primary: "#ffabef",
        "outline-variant": "#564051",
        outline: "#a4899c",
        "primary-fixed": "#ffd7f3",
        tertiary: "#d1bcff",
        "on-error": "#690005",
        "on-primary-fixed": "#390036",
        "on-primary-container": "#51004d",
        "surface-variant": "#383244",
        "on-background": "#e9def6",
        "on-error-container": "#ffdad6",
        "inverse-surface": "#e9def6",
        "tertiary-container": "#a178ff",
        "on-tertiary": "#3c0090",
        "secondary-container": "#00eefc",
        "surface-container-low": "#1e1929",
        "on-secondary-container": "#00686f",
        "on-secondary": "#00363a",
        surface: "#161121",
        "on-surface": "#e9def6",
        "primary-container": "#ff0df5",
        "surface-container-high": "#2d2739",
        "secondary-fixed": "#7df4ff",
        "primary-fixed-dim": "#ffabef",
        "surface-container-lowest": "#100b1b",
        "secondary-fixed-dim": "#00dbe9",
        "error-container": "#93000a",
        "surface-tint": "#ffabef",
        "surface-container-highest": "#383244",
        "inverse-primary": "#aa00a3",
        "on-surface-variant": "#dcbed3",
        "on-primary": "#5c0058",
        "surface-dim": "#161121",
        obsidian: "#0f0a1a",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        "2xl": "0.75rem",
        full: "9999px",
      },
      spacing: {
        "margin-mobile": "20px",
        "container-max": "1280px",
        gutter: "16px",
        "margin-desktop": "64px",
        unit: "4px",
      },
      maxWidth: {
        "container-max": "1280px",
      },
      fontFamily: {
        display: ["var(--font-geist-sans)", "sans-serif"],
        body: ["var(--font-geist-sans)", "sans-serif"],
        mono: ["var(--font-geist-mono)", "monospace"],
      },
      fontSize: {
        "headline-xl": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "mono-data": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
} satisfies Config;
